_wandb:
    value:
        cli_version: 0.19.11
        m:
            - "1": train_accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": batch
              "6":
                - 3
              "7": []
            - "1": train_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_accuracy
              "5": 5
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "6":
                - 3
              "7": []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 55
                - 77
            "2":
                - 1
                - 55
                - 77
            "3":
                - 2
                - 7
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.11
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
batch_size:
    value: 64
device:
    value: cpu
epochs:
    value: 5
hidden_dim:
    value: 152
input_dim:
    value: 3
lr:
    value: 0.001
